camel.jbang.dependencies=camel-openai

camel.component.openai.apiKey={{env:OPENAI_API_KEY}}
camel.component.openai.baseUrl={{env:OPENAI_BASE_URL}}
camel.component.openai.model={{env:OPENAI_MODEL}}

camel.main.durationMaxMessages=1